server:
  port: 9003
  servlet:
    context-path: /

spring:
  application:
    name: offcnpe_customer
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    host: 192.168.186.128
    port: 6379
    password: 123456

dubbo:
  scan:
    base-packages: com.ujiuye.controller,com.ujiuye.service
  registry:
    address: zookeeper://192.168.186.129:2181
    timeout: 100000

fileUploadPath: D:/upload/